---
- hosts: digitalocean

  vars:
    do_token: dd64febaf883c65bcd487c2156815a0a74d4ec2ccafac5c96aa1aee16d6856ff

  tasks:
  
  - name: ensure key exists at DigitalOcean
    digital_ocean: >
      state=present
      command=ssh
      name=my_ssh_key
      ssh_pub_key={{ lookup('file', 'id_rsa.pub') }}
      api_token={{ do_token }}
    register: my_ssh_key

  - name: ensure droplet one exists
    digital_ocean: >
      state=absent
      command=droplet
      name=droplet-one
      size_id=512mb
      region_id=sgp1
      unique_name=yes
      image_id=ubuntu-14-04-x64
      ssh_key_ids={{ my_ssh_key.ssh_key.id }}
      api_token={{ do_token }}
    register: my_droplet

  - name: ensure droplet one exists
    digital_ocean: >
      state=present
      command=droplet
      name=droplet-two
      size_id=512mb
      region_id=sgp1
      unique_name=yes
      image_id=ubuntu-14-04-x64
      ssh_key_ids={{ my_ssh_key.ssh_key.id }}
      api_token={{ do_token }}
    register: my_droplet2

  - debug: msg="ID is {{ my_droplet2.droplet.id }}"
  - debug: msg="IP is {{ my_droplet2.droplet.ip_address }}"
